// components/IndexContent.vue
<template>
  <v-layout
    :row="isLandscape"
    :column="!isLandscape"
    fill-height
    align-center
    justify-center
  >
    <v-flex
      xs6
      class="content-section"
    >
      <v-layout
        fill-height
        align-center
        justify-center
      >
        <v-img
          :src="titleImage"
          alt="'1부터 30까지!' 로고"
          aspect-ratio="1"
          max-width="256"
          class="game-logo"
        />
      </v-layout>
    </v-flex>
    <v-flex
      xs6
      class="content-section"
    >
      <v-layout
        fill-height
        align-center
        :justify-center="!isLandscape"
      >
        <v-flex
          :xs9="isLandscape"
          :offset-xs1="isLandscape"
          :xs10="!isLandscape"
          class="menu-wrapper"
        >
          <v-item-group>
            <v-layout
              v-for="(menu, index) in menus"
              :key="index"
              justify-center
            >
              <v-flex>
                <v-item>
                  <v-btn
                    block
                    :color="(index % 2 === 1 ? 'deep-brown-like' : 'amber-like')"
                    :light="index % 2 === 0"
                    :dark="index % 2 === 1"
                    @click="navigateContent(menu.to)"
                  >
                    <v-icon
                      left
                    >
                      {{ menu.icon }}
                    </v-icon>
                    <span>{{ menu.title }}</span>
                  </v-btn>
                </v-item>
              </v-flex>
            </v-layout>
          </v-item-group>
        </v-flex>
      </v-layout>
    </v-flex>
  </v-layout>
</template>

<script>
import titleImage from '~/assets/images/icon-256.png'

export default {
  name: 'IndexContent',
  data () {
    return {
      titleImage,
      menus: [
        {
          icon: 'fas fa-th',
          title: '게임 시작',
          to: '/game'
        },
        {
          icon: 'fas fa-trophy',
          title: '기록 확인',
          to: '/ranking'
        }
      ]
    }
  },
  methods: {
    navigateContent (path) {
      this.$store.commit('navigateContent', path)
    }
  }
}
</script>

<style lang="scss" scoped>
.v-item-group > * {
  cursor: auto;
}

@media (orientation: portrait) {
  .content-section {
    width: 100%;
  }

  .game-logo {
    margin-top: calc(((100vh - 24px * 2) * 6 / 12 - 256px) / 2);
  }
}

@media (orientation: portrait) and (max-width: 959px) {
  .game-logo {
    margin-top: calc(((100vh - 16px * 2) * 6 / 12 - 256px) / 2);
  }
}

@media (orientation: landscape) {
  .content-section {
    height: 100%;
  }

  .game-logo {
    margin-left: calc(((100vw - 24px * 2) * 6 / 12 - 256px) / 2);
  }

  .menu-wrapper {
    max-width: 320px;
  }
}

@media (orientation: landscape) and (max-width: 959px) {
  .game-logo {
    margin-left: calc(((100vw - 16px * 2) * 6 / 12 - 256px) / 2);
  }
}
</style>

// src/components/contents/IndexContent.tsx
import Image from 'next/image';
import { useSetRecoilState } from 'recoil';
import { classNames } from '@/adaptors';
import { contentState } from '@/store/atoms';
import { VeeLayout, VeeFlex, VeeButton, VeeIcon } from '@/components/vuetify-imitation';
import { ContentEnum } from '@/types';
import logoImage from '@/assets/images/icon-256.png';

export default function IndexContent() {
  const setContent = useSetRecoilState(contentState);

  return (
    <VeeLayout className="h-full items-center justify-center portrait:flex-col">
      <VeeFlex className="grow-0 basis-1/2 portrait:w-full landscape:h-full">
        <VeeLayout className="h-full items-center justify-center">
          <Image
            className={classNames(
              `portrait:mt-[calc((((100vh-16px*2)*6/12)-256px)/2)]
              portrait:md:mt-[calc((((100vh-24px*2)*6/12)-256px)/2)]
              landscape:ml-[calc((((100vw-16px*2)*6/12)-256px)/2)]
              landscape:md:ml-[calc((((100vw-24px*2)*6/12)-256px)/2)]`,
            )}
            src={logoImage}
            alt="1부터30까지 로고"
            width={256}
            height={256}
            priority
          />
        </VeeLayout>
      </VeeFlex>
      <VeeFlex className="grow-0 basis-1/2 portrait:w-full landscape:h-full">
        <VeeLayout className="h-full items-center portrait:justify-center">
          <VeeFlex
            className={classNames(
              `grow-0 portrait:basis-5/6 landscape:ml-[8.333333%] landscape:max-w-[320px]
              landscape:basis-3/4`,
            )}
          >
            <VeeLayout className="justify-center">
              <VeeFlex>
                <VeeButton
                  className="!mx-0 flex w-full flex-1 bg-legacy-amber"
                  onClick={() => setContent(ContentEnum.game)}
                >
                  <VeeIcon className="fas fa-th mr-4" />
                  <span className="text-[16px]">게임 시작</span>
                </VeeButton>
              </VeeFlex>
            </VeeLayout>
            <VeeLayout className="justify-center">
              <VeeFlex>
                <VeeButton
                  className="!mx-0 flex w-full flex-1 bg-legacy-brown text-white"
                  onClick={() => setContent(ContentEnum.ranking)}
                >
                  <VeeIcon className="fas fa-trophy mr-4" />
                  <span className="text-[16px]">기록 확인</span>
                </VeeButton>
              </VeeFlex>
            </VeeLayout>
          </VeeFlex>
        </VeeLayout>
      </VeeFlex>
    </VeeLayout>
  );
}
